#!/usr/bin/env bash
# Fixes the issue with the server
useradd -m -s /bin/bash nginx
sed -i 's/user\s*=\s*www-data/user = nginx/' /etc/nginx/nginx.conf
service nginx restart
ps aux | grep '[n]ginx'
nc -z 0 8080
ps aux | grep '[n]ginx' | grep -q nginx
