#!/usr/bin/env bash
# This script installs and configures HAProxy on lb-01 server

# Ensure script is run as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root (use sudo)"
    exit 1
fi

# Install HAProxy
apt-get update
apt-get install -y haproxy

# Create HAProxy configuration file
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend main
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    balance roundrobin
    server web-01 18.234.238.225:80 check
    server web-02 54.174.65.83:80 check
EOF

# Restart HAProxy to apply changes
service haproxy restart

